// Every word the lab's page shows of its own, in English and in Russian: one table, and the page takes the Russian
// one when the browser's first language is Russian. An entry is a text, or a function of what goes into it. The
// page's markup holds the English texts and names an entry in `data-t` (the element's text), `data-t-title`,
// `data-t-placeholder` or `data-t-label`; `app.js` asks for the rest by name.
const en = {
  point: '.', day: 'day', dayShort: 'd', seconds: 's', minutes: 'min', hours: 'h', wholeDay: 'a day',
  title: 'sagents lab', titleOf: name => `${name} · sagents lab`,
  // An event of the feed.
  drives: 'drives', pullsUp: 'has pulled up', crosses: 'crosses the door', fare: 'fare', calls: 'calls', does: 'does', goes: 'goes', arrives: 'arrives', waits: 'waits', fallsAsleep: 'falls asleep', wakes: 'wakes', worldTag: 'world', whatCame: 'what came of it',
  nothingNoticed: 'nothing that could be noticed', answers: 'answers', noAnswer: 'does not answer', weather: 'weather', memoryRewritten: 'memory rewritten', memoryLost: ' — lost',
  memoryMissing: 'The rewrite failed: what was to stay is forgotten.', cut: '(cut)', heardBy: 'heard by', indoors: 'Under a roof',
  search: 'search', searchText: 'the world took this for a search of the place', found: 'found', moved: 'moved', movedStock: 'moved from stock', as: 'as', state: 'state', pose: 'pose', none: 'none',
  feels: 'feels', wakesList: 'wakes', beyond: 'heard next door', gesture: 'gesture', says: 'says with it',
  noteLabel: 'to oneself', unfold: '▸ unfold', fold: '▾ fold',
  why: { to: 'addressed to', heard: 'hears', body: 'concerns' },
  // The feed and its marks.
  onlyStretch: 'only this stretch', toChapterTitle: 'Read the chapter that retells this stretch', aloneTitle: 'Open this stretch by itself, without the rest of the world',
  eventsN: n => `events ${n}`, loading: 'loading…', chapterLink: (n, title) => `chapter ${n}${title ? ` · ${title}` : ''} →`, fresh: n => `↓ new: ${n}`, shown: (n, all) => `shown ${n} of ${all}`,
  emptyFiltered: 'No event passes these filters.', emptyGone: 'There is no such experiment here.', emptyNone: 'No events yet.', countOf: (at, all) => `${at} of ${all}`, noHits: 'none',
  // The list of experiments.
  oneRun: 'one run directory', running: 'running', compare: 'compare', sideA: 'A', sideB: 'B', sideBoth: 'A and B', residents: 'residents', world: 'world', clock: 'clock',
  stretches: 'stretches', events: 'events', requests: 'requests', chapters: 'chapters', cmpRemove: 'remove the comparison', cmpStretches: 'compare stretches', cmpWithOpen: 'compare with the open one',
  narrow: 'Narrow by a part of a name', rehearsals: n => `rehearsals: ${n}`, rehearsal: 'rehearsal', textOnly: 'transcript only', noMatch: 'No experiment has this in its name.',
  listEmpty: 'No experiments under the lab’s roots yet: a directory with world.json, a file *.events.jsonl or a transcript is waited for.', sideLabel: 'Experiments of the lab', bSide: 'List of experiments (E)',
  // The top of the page.
  wholeWorld: 'the whole world', noLink: 'no connection', notGrowing: 'not growing', noLinkTitle: 'The server does not answer: it was stopped, or started again at another address.',
  growingTitle: 'A file of the run grew in the last seconds.', loaded: (ready, all) => `stretches loaded ${ready} of ${all}`, fromCache: 'from cache', answer: 'answer', keyTitle: key => `Key ${key}`,
  stretchTitle: 'A stretch of the run: in the feed of a world it goes to where the stretch begins', soloTitle: 'Show this one stretch, without the rest of the world', solo: 'only the stretch',
  clockTitle: 'The story clock at the lowest event in the window', feed: 'Feed', feedTitle: 'Feed', story: 'Story', storyTitle: 'Story: the narrator’s chapters (S)', numbers: 'Numbers', numbersTitle: 'Numbers (N)',
  text: 'Transcript', textTitle: 'Transcript: the run as the command line printed it (X)', follow: 'follow', followTitle: 'Keep the newest in view (F)', faceTitle: 'The face of the text: with serifs or without',
  helpTitle: 'Keys (?)', who: 'Who', where: 'Where', searchHint: 'Search in the text ( / )', prevTitle: 'Previous (Shift+Enter)', nextTitle: 'Next (Enter)', onlyFound: 'only what was found',
  thoughts: 'thoughts', thoughtsTitle: 'Private notes and rewritten memory (M)', lists: 'lists of the world', listsTitle: 'What moved, poses, what a body feels (L)', clear: 'Clear ✕', clearTitle: 'Take off every filter and the search (0)',
  stripTitle: 'The whole world by the story clock: a click or a drag goes there',
  // The map.
  map: 'Map', mapTitle: 'Map: the places of the world and who is where (P)', mapPrev: 'The previous move (K)', mapNext: 'The next move (J)', mapMoment: 'The moment of the story that the map shows',
  mapLeft: 'the map is of the left experiment alone', mapLoading: 'the map is loading…', mapOnWay: (from, to, clock) => `${from} → ${to}, due ${clock}`, mapDue: (to, clock) => `→ ${to} ${clock}`, mapAsleep: 'asleep',
  mapUnknown: 'not yet known', mapMany: count => `${count} travellers`, mapNowhere: 'in no place of the world file', mapHere: 'here now', mapNobody: 'nobody is here now', mapFigures: 'of the place, played by nobody', mapWays: 'from here',
  mapFilter: 'A click puts the place into the feed’s filter by place, or takes it out.', mapFiltered: 'in the feed’s filter',
  keyRoof: 'under a roof', keyOpen: 'under the open sky', keyDoor: 'next door: a door or a thin wall', keyLink: 'a way between groups, not to scale', keyAsleep: 'asleep',
  keyScale: 'Each grey group is drawn to a scale of its own: the rule in its corner.',
  // The comparison.
  rightStretch: 'The stretch on the right', rowSpan: 'How much story time one row holds', cmpClose: 'Remove the comparison (C)', auto: 'auto',
  // The numbers.
  kinds: { turn: 'residents’ turns', world: 'answers of the world', reply: 'answers of figures', memory: 'memory' },
  fewRequests: 'Too few requests with counted tokens to draw.', allRequests: 'all requests', chartLabel: 'The share of input tokens read from the cache as the run went', requestN: n => `request ${n}`,
  chartTip: (from, to, all, turn, world) => `requests ${from}–${to}: all ${all}, turns ${turn}, world ${world}`, storyClock: 'story clock', notWhole: (ready, all) => `stretches loaded ${ready} of ${all}, the numbers are not whole yet`,
  tRequests: 'Requests', tInput: 'Input, tokens', tCache: 'From cache', tOutput: 'Output, tokens', tReasoning: 'Reasoning, tokens', tAnswer: 'Answer, median', tFailures: 'Failures',
  noUsageWorld: 'This world has no usage rows.', noUsageStretch: 'This stretch has no usage rows.', byKind: 'By kind of request', input: 'input', output: 'output', reasoning: 'reasoning', median: 'median',
  model: 'model', total: 'total', cacheShare: 'Share of input from the cache as the run went', byCharacter: 'By character', speeches: 'speeches', deeds: 'deeds', walks: 'walks', notes: 'notes', turns: 'turns',
  memory: 'memory', stretchesOf: 'Stretches of the experiment',
  // The story and the transcript.
  toFeed: name => `to the feed: ${name} →`, toFeedTitle: name => `Open the feed where the stretch ${name} begins`, storyCount: (chapters, told, all) => `chapters ${chapters} · stretches retold ${told} of ${all}`,
  chaptersLoading: 'The chapters are loading…', noChapters: 'No chapters yet: the narrator writes them into the folder story of the run.', chapter: n => `Chapter ${n}`, noSuchStretch: 'The run has no such stretch',
  retoldBy: model => `retold by: ${model}`, untold: 'Not retold yet:', noText: 'This experiment has no transcript.',
  textOnlyNote: 'This run kept no events: only its transcript can be shown.', bytes: 'bytes',
  // Theme and help.
  themes: { '': 'as the system', light: 'light', dark: 'dark' }, themeTitle: name => `Theme: ${name} (T)`, keys: 'Keys', close: 'Close',
  kSearch: 'search in the text; Enter and Shift+Enter go to the next and the previous', kWho: 'put a character in the focus, or take it out, by number', kClear: 'take off every filter and the search',
  kFollow: 'follow the newest', kStep: 'the next and the previous event; on the map, the next and the previous move', kEnds: 'to the top and to the bottom', kNumbers: 'the feed or the numbers', kStory: 'the feed or the story: the narrator’s chapters',
  kText: 'the feed or the transcript', kMap: 'the feed or the map: the places and who is where', kCompare: 'the comparison: with the next experiment, or off', kExperiments: 'the previous and the next experiment', kList: 'the list of experiments',
  kSwitches: 'thoughts; lists of the world', kTheme: 'the theme', kHelp: 'this help; Esc closes it',
  focusNote: 'A focus on characters keeps what they said, did and wrote down, what came of their deeds, what their bodies felt, what was addressed to them and what they heard. The thoughts and the feelings of others are hidden then.',
};
const ru = {
  point: ',', day: 'день', dayShort: 'д', seconds: 'с', minutes: 'мин', hours: 'ч', wholeDay: 'сутки',
  title: 'Лаборатория sagents', titleOf: name => `${name} · лаборатория sagents`,
  drives: 'ведёт', pullsUp: 'подъезжает', crosses: 'проходит через дверь', fare: 'плата за проезд', calls: 'звонит', does: 'делает', goes: 'идёт', arrives: 'приходит', waits: 'ждёт', fallsAsleep: 'засыпает', wakes: 'просыпается', worldTag: 'мир', whatCame: 'что вышло',
  nothingNoticed: 'ничего заметного', answers: 'отвечает', noAnswer: 'не отвечает', weather: 'погода', memoryRewritten: 'память переписана', memoryLost: ' — утрачена',
  memoryMissing: 'Переписать не удалось: то, что должно было остаться, забыто.', cut: '(обрезано)', heardBy: 'слышат', indoors: 'Под крышей',
  search: 'поиск', searchText: 'мир счёл это обыском места', found: 'найдено', moved: 'перешло', movedStock: 'перешло из запаса', as: 'как', state: 'состояние', pose: 'поза', none: 'нет',
  feels: 'чувствует', wakesList: 'будит', beyond: 'слышно по соседству', gesture: 'жест', says: 'говорит при этом',
  noteLabel: 'про себя', unfold: '▸ раскрыть', fold: '▾ свернуть',
  why: { to: 'обращено к', heard: 'слышит', body: 'касается' },
  onlyStretch: 'только этот отрезок', toChapterTitle: 'Читать главу, в которой пересказан этот отрезок', aloneTitle: 'Открыть этот отрезок отдельно, без остального мира',
  eventsN: n => `событий ${n}`, loading: 'загружается…', chapterLink: (n, title) => `глава ${n}${title ? ` · ${title}` : ''} →`, fresh: n => `↓ новые: ${n}`, shown: (n, all) => `показано ${n} из ${all}`,
  emptyFiltered: 'Под эти фильтры не попало ни одного события.', emptyGone: 'Такого эксперимента здесь нет.', emptyNone: 'Событий пока нет.', countOf: (at, all) => `${at} из ${all}`, noHits: 'нет',
  oneRun: 'одна папка прогона', running: 'идёт', compare: 'сравнить', sideA: 'А', sideB: 'Б', sideBoth: 'А и Б', residents: 'жители', world: 'мир', clock: 'часы',
  stretches: 'отрезков', events: 'событий', requests: 'запросов', chapters: 'глав', cmpRemove: 'убрать сравнение', cmpStretches: 'сравнить отрезки', cmpWithOpen: 'сравнить с открытым',
  narrow: 'Часть названия', rehearsals: n => `репетиции: ${n}`, rehearsal: 'репетиция', textOnly: 'только текст', noMatch: 'Ни в одном названии этого нет.',
  listEmpty: 'В лаборатории пока нет экспериментов: ждём папку с world.json, файл *.events.jsonl или текст прогона.', sideLabel: 'Эксперименты лаборатории', bSide: 'Список экспериментов (E)',
  wholeWorld: 'весь мир', noLink: 'нет связи', notGrowing: 'не растёт', noLinkTitle: 'Сервер не отвечает: он остановлен или запущен заново с другим адресом.',
  growingTitle: 'Файл прогона рос в последние секунды.', loaded: (ready, all) => `загружено отрезков ${ready} из ${all}`, fromCache: 'из кэша', answer: 'ответ', keyTitle: key => `Клавиша ${key}`,
  stretchTitle: 'Отрезок прогона: в ленте мира переносит туда, где он начинается', soloTitle: 'Показать один этот отрезок, без остального мира', solo: 'только отрезок',
  clockTitle: 'Часы истории на нижнем видимом событии', feed: 'Лента', feedTitle: 'Лента', story: 'История', storyTitle: 'История: главы рассказчика (S)', numbers: 'Числа', numbersTitle: 'Числа (N)',
  text: 'Текст', textTitle: 'Текст: прогон, как его напечатала командная строка (X)', follow: 'следить', followTitle: 'Держать в виду самое новое (F)', faceTitle: 'Шрифт текста: с засечками или без',
  helpTitle: 'Клавиши (?)', who: 'Кто', where: 'Где', searchHint: 'Поиск в тексте ( / )', prevTitle: 'Предыдущее (Shift+Enter)', nextTitle: 'Следующее (Enter)', onlyFound: 'только найденное',
  thoughts: 'мысли', thoughtsTitle: 'Личные заметки и переписанная память (M)', lists: 'списки мира', listsTitle: 'Что переместилось, позы, что чувствует тело (L)', clear: 'Сбросить ✕', clearTitle: 'Снять все фильтры и поиск (0)',
  stripTitle: 'Весь мир по часам истории: щелчок или перетаскивание переносит туда',
  map: 'Карта', mapTitle: 'Карта: места мира и кто где (P)', mapPrev: 'Предыдущее перемещение (K)', mapNext: 'Следующее перемещение (J)', mapMoment: 'Момент истории, который показывает карта',
  mapLeft: 'карта только левого эксперимента', mapLoading: 'карта загружается…', mapOnWay: (from, to, clock) => `${from} → ${to}, будет в ${clock}`, mapDue: (to, clock) => `→ ${to} ${clock}`, mapAsleep: 'спит',
  mapUnknown: 'пока неизвестно', mapMany: count => `${count} в пути`, mapNowhere: 'ни в одном месте из файла мира', mapHere: 'сейчас здесь', mapNobody: 'сейчас здесь никого', mapFigures: 'люди места, которых никто не играет', mapWays: 'отсюда',
  mapFilter: 'Щелчок добавляет место в фильтр ленты по месту или убирает его.', mapFiltered: 'в фильтре ленты',
  keyRoof: 'под крышей', keyOpen: 'под открытым небом', keyDoor: 'по соседству: дверь или тонкая стена', keyLink: 'путь между группами, не в масштабе', keyAsleep: 'спит',
  keyScale: 'У каждой серой группы свой масштаб: линейка в её углу.',
  rightStretch: 'Отрезок справа', rowSpan: 'Сколько времени истории в одной строке', cmpClose: 'Убрать сравнение (C)', auto: 'авто',
  kinds: { turn: 'ходы жителей', world: 'ответы мира', reply: 'ответы фигур', memory: 'память' },
  fewRequests: 'Мало запросов со счётом токенов, чтобы рисовать.', allRequests: 'все запросы', chartLabel: 'Доля входных токенов, прочитанных из кэша, по ходу прогона', requestN: n => `запрос ${n}`,
  chartTip: (from, to, all, turn, world) => `запросы ${from}–${to}: все ${all}, ходы ${turn}, мир ${world}`, storyClock: 'часы истории', notWhole: (ready, all) => `загружено отрезков ${ready} из ${all}, числа пока неполные`,
  tRequests: 'Запросов', tInput: 'Вход, токенов', tCache: 'Из кэша', tOutput: 'Выход, токенов', tReasoning: 'Рассуждение, токенов', tAnswer: 'Ответ, медиана', tFailures: 'Сбоев',
  noUsageWorld: 'Строк usage для этого мира нет.', noUsageStretch: 'Строк usage для этого отрезка нет.', byKind: 'По виду запроса', input: 'вход', output: 'выход', reasoning: 'рассужд.', median: 'медиана',
  model: 'модель', total: 'всего', cacheShare: 'Доля входа из кэша по ходу прогона', byCharacter: 'По героям', speeches: 'реплик', deeds: 'дел', walks: 'переходов', notes: 'заметок', turns: 'ходов',
  memory: 'память', stretchesOf: 'Отрезки эксперимента',
  toFeed: name => `в ленту: ${name} →`, toFeedTitle: name => `Открыть ленту там, где начинается отрезок ${name}`, storyCount: (chapters, told, all) => `глав ${chapters} · пересказано отрезков ${told} из ${all}`,
  chaptersLoading: 'Главы загружаются…', noChapters: 'Глав пока нет: рассказчик пишет их в папку story прогона.', chapter: n => `Глава ${n}`, noSuchStretch: 'Такого отрезка в прогоне нет',
  retoldBy: model => `пересказ: ${model}`, untold: 'Ещё не пересказано:', noText: 'У этого эксперимента нет текста прогона.',
  textOnlyNote: 'От этого прогона не осталось событий: показать можно только его текст.', bytes: 'байт',
  themes: { '': 'как в системе', light: 'светлая', dark: 'тёмная' }, themeTitle: name => `Тема: ${name} (T)`, keys: 'Клавиши', close: 'Закрыть',
  kSearch: 'поиск в тексте; Enter и Shift+Enter — следующее и предыдущее', kWho: 'включить или снять героя по номеру', kClear: 'сбросить все фильтры и поиск',
  kFollow: 'следить за новым', kStep: 'следующее и предыдущее событие; на карте следующее и предыдущее перемещение', kEnds: 'в начало и в конец', kNumbers: 'лента или числа', kStory: 'лента или история: главы рассказчика',
  kText: 'лента или текст прогона', kMap: 'лента или карта: места и кто где', kCompare: 'сравнение: включить с соседним экспериментом или убрать', kExperiments: 'предыдущий и следующий эксперимент', kList: 'список экспериментов',
  kSwitches: 'мысли; списки мира', kTheme: 'тема', kHelp: 'эта подсказка; Esc закрывает',
  focusNote: 'Фокус на героях оставляет то, что они сказали, сделали и записали, что вышло из их дел, что чувствовало их тело, что обращено к ним и что они слышали. Чужие мысли и чужие ощущения при этом скрыты.',
};
export const STRINGS = { en, ru };
// The language of the page: the one chosen when the lab was started (`lang` in the address, `en` or `ru`), and with
// none Russian for a browser whose first language is Russian, English for any other.
export const languageOf = (language, chosen = null) => chosen === 'en' || chosen === 'ru' ? chosen : /^ru(?:-|$)/i.test(String(language ?? '')) ? 'ru' : 'en';
